version: '3.8'

services:
  node-monitor:
    build: .
    container_name: node-monitor
    env_file:
      - .env
    volumes:
      - ./data/servers.db:/app/servers.db  
      - ./logs:/app/logs                  
    restart: unless-stopped